openai:
  endpoint: "api.com"
  api_key: "jaksjdfjaklsdf"
  models:
    - name: "gpt-4o"
      temp: "0.7"
      system_prompt: "yada yada yada"
    - name: "gpt-4.5"
      temp: "0.7"
      system_prompt: "yada yada yada"
ollama_local:
  endpoint: "localhost"
  api_key: "blah blah"
  models:
    - name: "deepseek-r1"
      temp: "0.7"
      system_prompt: "yada yada yada"
    - name: "llama3.3"
      temp: "0.7"
      system_prompt: "yada yada yada"
